import { DerechoARCOPDetalle } from '../types';

export const CATALOGO_DERECHOS_ARCOP: DerechoARCOPDetalle[] = [
  {
    tipo: 'Bloqueo Temporal',
    articulo: 'Art. 10 bis',
    sla: '2 días hábiles',
    esCritico: true,
    resumen: 'Congela de inmediato cualquier uso o comunicación del dato mientras se resuelve una controversia.',
    descripcionCompleta: 'El titular puede exigir la suspensión temporal de las operaciones de tratamiento cuando se cuestione la exactitud de los datos o la licitud del tratamiento. Es el SLA más estricto de toda la Ley 21.719.',
    requisitosTitular: 'Individualización del titular, indicación precisa de los datos cuestionados y fundamento de la controversia.',
    obligacionEmpresa: 'Suspender todo tratamiento técnico y comercial en un plazo improrrogable de 2 días hábiles, aislar el dato en servidores y notificar al titular la medida cautelar adoptada.',
    excepcionesLegales: 'No procede levantar el bloqueo unilateralmente sin antes haber resuelto la controversia de fondo o acreditar una orden judicial en contrario.',
    reclamacionAPDP: 'El retraso superior a 48 horas faculta al titular a denunciar directamente ante la APDP, configurando infracción grave (Art. 41 letra e).',
  },
  {
    tipo: 'Acceso',
    articulo: 'Art. 5',
    sla: '30 días corridos',
    resumen: 'Conocer qué datos personales de la persona mantiene la empresa, con qué fin y a quién se transmiten.',
    descripcionCompleta: 'El titular tiene derecho a solicitar y obtener información clara sobre si sus datos están siendo tratados, el origen de los mismos, los fines del tratamiento, el plazo de conservación y los destinatarios o encargados a quienes se hayan transferido.',
    requisitosTitular: 'Acreditar identidad fehacientemente (cédula chilena o poder notarial del representante legal).',
    obligacionEmpresa: 'Emitir un informe estructurado y comprensible con la información registrada en el Registro de Actividades de Tratamiento (RAT - Art. 14 ter), sin cobro alguno para el titular.',
    excepcionesLegales: 'Podrá denegarse motivadamente cuando afecte derechos de terceros, el secreto comercial o la seguridad nacional.',
    reclamacionAPDP: 'Si no se entrega en 30 días, el titular puede interponer reclamo ante la APDP para que ordene la entrega bajo apercibimiento de multa.',
  },
  {
    tipo: 'Rectificación',
    articulo: 'Art. 6',
    sla: '30 días corridos',
    resumen: 'Corregir o actualizar información personal que sea inexacta, incompleta o desactualizada.',
    descripcionCompleta: 'Obliga a la empresa a modificar o complementar los datos erróneos en todas sus bases activas y comunicar la rectificación a los encargados y terceros que hayan recibido previamente dicha información.',
    requisitosTitular: 'Identificar con precisión el dato erróneo y acompañar los antecedentes que respalden la corrección solicitada.',
    obligacionEmpresa: 'Actualizar las bases en un plazo de 30 días corridos y notificar fehacientemente al titular una vez corregido el registro.',
    excepcionesLegales: 'Cuando los antecedentes acompañados sean manifiestamente contradictorios o no logren acreditar el error alegado.',
    reclamacionAPDP: 'En caso de rechazo infundado, la APDP puede instruir la rectificación forzosa con costas a la empresa.',
  },
  {
    tipo: 'Supresión',
    articulo: 'Art. 7',
    sla: '30 días corridos',
    resumen: 'Eliminar o borrar datos cuando hayan dejado de ser necesarios o no cuenten con base legal.',
    descripcionCompleta: 'También denominado "derecho al olvido", procede cuando el tratamiento carezca de base de licitud, el titular haya revocado su consentimiento, o los datos hayan cumplido el plazo de retención previsto en el RAT.',
    requisitosTitular: 'Especificar las razones por las cuales estima que los datos deben ser borrados o acreditar la revocación de consentimiento.',
    obligacionEmpresa: 'Eliminar de forma irreversible el dato, o anonimizarlo de manera que impida la reidentificación del titular.',
    excepcionesLegales: 'No procede la supresión si existe obligación legal de conservación: registros tributarios (5 años por Código Tributario) o antecedentes laborales y previsionales.',
    reclamacionAPDP: 'Continuar usando datos tras una supresión legalmente procedente constituye infracción grave o gravísima ante la APDP.',
  },
  {
    tipo: 'Oposición',
    articulo: 'Art. 8',
    sla: '30 días corridos',
    resumen: 'Exigir el cese del tratamiento con fines de marketing, publicidad o analítica de perfiles.',
    descripcionCompleta: 'El titular puede oponerse en cualquier momento al uso de sus datos personales para fines de prospección comercial, publicidad directa, telemarketing o tratamientos sustentados en el interés legítimo.',
    requisitosTitular: 'Expresar su voluntad de no recibir más comunicaciones publicitarias o de oponerse al tratamiento específico.',
    obligacionEmpresa: 'Cesar de manera inmediata y definitiva el envío de comunicaciones y dar de baja al titular de listas de difusión.',
    excepcionesLegales: 'No aplica cuando el tratamiento sea imprescindible para la ejecución de un contrato vigente (ej. facturación de un servicio contratado).',
    reclamacionAPDP: 'Ignorar la oposición publicitaria habilita al titular a denunciar ante el SERNAC y la APDP por spam reiterado.',
  },
  {
    tipo: 'Portabilidad',
    articulo: 'Art. 9',
    sla: '30 días corridos',
    resumen: 'Recibir una copia digital estructurada de los datos para transferirlos a otro proveedor.',
    descripcionCompleta: 'Faculta al titular a obtener una copia de sus datos personales en un formato estructurado, genérico y legible por máquina (ej. JSON, XML o CSV) o solicitar su traspaso directo a otro proveedor cuando sea técnicamente factible.',
    requisitosTitular: 'Indicar el formato digital preferido o las especificaciones del prestador de destino.',
    obligacionEmpresa: 'Poner a disposición del titular el archivo electrónico interoperable sin costo adicional en un plazo de 30 días corridos.',
    excepcionesLegales: 'Tratamientos que no se basen en consentimiento ni en ejecución de contrato, o cuando suponga revelar secretos industriales del responsable.',
    reclamacionAPDP: 'La negativa arbitraria a facilitar la portabilidad es sancionable por la APDP como infracción grave.',
  },
];
