import { ActividadRAT } from '../types';

export const ACTIVIDADES_PREDEFINIDAS_RAT: ActividadRAT[] = [
  {
    id: 'act-rrhh',
    categoria: 'rrhh',
    nombre: 'Gestión de Personal y Planilla de Remuneraciones',
    finalidad: 'Contratación laboral, pago de sueldos, liquidaciones, cotizaciones previsionales (Previred) y registro de asistencia.',
    titulares: ['Trabajadores contratados', 'Cargas familiares', 'Ex-trabajadores'],
    datosTratados: ['Nombres y Apellidos', 'RUT chileno', 'Domicilio', 'Cuenta bancaria', 'Sueldo pactado', 'Huella digital/reloj control', 'Licencias médicas (salud)'],
    contieneSensibles: true,
    categoriasSensibles: ['Salud (Licencias médicas)', 'Biométricos (Control de asistencia por huella/facial)', 'RUT'],
    baseLicitud: 'Art. 13 letra a) - Ejecución de contrato o relación laboral/comercial',
    justificacionLegal: 'Obligación del Código del Trabajo, DFL 1 y cumplimiento de obligaciones previsionales y tributarias.',
    almacenamiento: 'Sistema de RRHH en la nube / Software contable / Planillas seguras',
    plazoConservacion: 'Durante la relación laboral + 5 años post-término para fines de prescripción laboral y fiscal.',
    destinatarios: 'Previred, Dirección del Trabajo, SII, Entidades Bancarias y Mutuales.',
    medidasSeguridad: ['Acceso restringido por roles', 'Contraseñas con doble factor (MFA)', 'Cifrado en tránsito y reposo'],
    seleccionada: true,
  },
  {
    id: 'act-clientes-crm',
    categoria: 'clientes',
    nombre: 'Gestión Comercial, CRM y Servicio al Cliente',
    finalidad: 'Contacto comercial, cotizaciones, gestión de ventas B2B/B2C, soporte postventa y fidelización.',
    titulares: ['Clientes vigentes', 'Contactos de empresas clientes', 'Potenciales compradores (Leads)'],
    datosTratados: ['Nombre y Apellido', 'RUT de facturación', 'Correo electrónico', 'Teléfono móvil', 'Historial de compras'],
    contieneSensibles: false,
    categoriasSensibles: [],
    baseLicitud: 'Art. 13 letra a) - Ejecución de contrato o relación laboral/comercial',
    justificacionLegal: 'Necesario para la ejecución de la relación comercial o medidas precontractuales solicitadas por el cliente.',
    almacenamiento: 'CRM en la nube (ej. HubSpot, Salesforce, Zoho, Google Drive)',
    plazoConservacion: 'Vigencia de la relación comercial + 3 años para soporte de garantías.',
    destinatarios: 'No se transfieren a terceros (uso estrictamente interno).',
    medidasSeguridad: ['Autenticación centralizada', 'Copias de respaldo periódicas', 'Cláusulas de confidencialidad con colaboradores'],
    seleccionada: true,
  },
  {
    id: 'act-ecommerce',
    categoria: 'ecommerce',
    nombre: 'Ventas en Sitio Web, Pagos y Despacho a Domicilio',
    finalidad: 'Procesamiento de compras online, emisión de boletas/facturas electrónicas y entrega logística.',
    titulares: ['Compradores online', 'Destinatarios de envíos'],
    datosTratados: ['Nombre', 'RUT', 'Dirección de envío', 'Teléfono', 'Email', 'Identificador de transacción pasarela'],
    contieneSensibles: false,
    categoriasSensibles: [],
    baseLicitud: 'Art. 13 letra a) - Ejecución de contrato o relación laboral/comercial',
    justificacionLegal: 'Perfeccionamiento y cumplimiento de la compraventa digital y entrega del producto.',
    almacenamiento: 'Plataforma eCommerce (Shopify, WooCommerce, Vtex)',
    plazoConservacion: '5 años conforme a exigencias del Código Tributario para comprobantes de venta.',
    destinatarios: 'Pasarelas de Pago (Webpay/Transbank, Mercado Pago), Empresas de Envíos (Chilexpress, Starken, Blue Express).',
    medidasSeguridad: ['Certificado SSL/TLS', 'Tokenización de pagos (no se almacenan números de tarjetas)', 'Políticas de contraseñas seguras'],
    seleccionada: true,
  },
  {
    id: 'act-cctv',
    categoria: 'seguridad',
    nombre: 'Circuito Cerrado de Televisión (CCTV) y Videovigilancia',
    finalidad: 'Seguridad física de instalaciones, prevención de delitos y resguardo de colaboradores y visitantes.',
    titulares: ['Trabajadores', 'Clientes presenciales', 'Proveedores y visitantes'],
    datosTratados: ['Imágenes en video', 'Hora y fecha de ingreso/salida', 'Fisonomía facial'],
    contieneSensibles: true,
    categoriasSensibles: ['Imágenes y datos biométricos fisonómicos'],
    baseLicitud: 'Art. 13 letra e) - Interés legítimo ponderado',
    justificacionLegal: 'Interés legítimo del responsable en proteger la vida e integridad física y los activos de la empresa, debidamente señalizado.',
    almacenamiento: 'DVR / NVR en sitio o almacenamiento en la nube con acceso cifrado',
    plazoConservacion: '30 días corridos, tras los cuales se sobreescriben automáticamente salvo incidente en investigación.',
    destinatarios: 'Ministerio Público o Carabineros de Chile sólo mediante orden judicial o requerimiento formal.',
    medidasSeguridad: ['Carteles visibles de advertencia en accesos', 'DVR bajo llave', 'Acceso exclusivo al jefe de seguridad'],
    seleccionada: true,
  },
  {
    id: 'act-marketing',
    categoria: 'marketing',
    nombre: 'Marketing Digital, Boletines y Prospección',
    finalidad: 'Envío de ofertas, promociones, invitaciones a eventos y analítica web.',
    titulares: ['Suscriptores de newsletter', 'Usuarios web'],
    datosTratados: ['Email', 'Nombre', 'Cookies analíticas', 'Intereses de navegación'],
    contieneSensibles: false,
    categoriasSensibles: [],
    baseLicitud: 'Art. 12 - Consentimiento expreso e informado',
    justificacionLegal: 'Consentimiento previo, libre, informado y específico del titular con mecanismo fácil de revocación (Opt-out).',
    almacenamiento: 'Herramienta de Email Marketing (Mailchimp, Brevo, Klaviyo)',
    plazoConservacion: 'Hasta que el titular solicite la baja (revocación de consentimiento) o 24 meses de inactividad.',
    destinatarios: 'Proveedores de analítica web y plataformas de distribución de correo bajo contrato de encargado de datos.',
    medidasSeguridad: ['Doble Opt-in de confirmación', 'Enlace directo de desuscripción en cada correo', 'Registros de trazabilidad del consentimiento'],
    seleccionada: false,
  },
  {
    id: 'act-proveedores',
    categoria: 'proveedores',
    nombre: 'Gestión y Pago a Proveedores y Prestadores de Servicios',
    finalidad: 'Emisión de órdenes de compra, recepción de facturas, pagos bancarios y cumplimiento tributario.',
    titulares: ['Proveedores personas naturales', 'Representantes legales de empresas proveedoras'],
    datosTratados: ['Razón social o Nombre', 'RUT', 'Cuenta corriente bancaria', 'Teléfono de contacto', 'Facturas DTE'],
    contieneSensibles: false,
    categoriasSensibles: [],
    baseLicitud: 'Art. 13 letra a) - Ejecución de contrato o relación laboral/comercial',
    justificacionLegal: 'Gestión contractual de adquisición de bienes o servicios y obligaciones tributarias con el SII.',
    almacenamiento: 'Software ERP / Portal bancario / Servidor interno',
    plazoConservacion: '5 años conforme a prescripción tributaria y mercantil.',
    destinatarios: 'Bancos e Instituciones Financieras, SII y Auditores contables.',
    medidasSeguridad: ['Perfiles de usuario bancario con apoderados', 'Doble factor en transferencias', 'Cifrado de planillas de pago'],
    seleccionada: true,
  },
];

export const DEFAULT_EMPRESA_RAT: Omit<import('../types').DatosEmpresaRAT, 'codigoCertificadoRAT'> = {
  razonSocial: 'Comercial & Servicios SpA',
  rutEmpresa: '76.845.120-K',
  representanteLegal: 'Carlos Muñoz Rojas',
  rubro: 'Servicios Profesionales y Comercio',
  clasificacionTamano: 'Pequeña Pyme',
  responsableTratamientoDPO: 'Carlos Muñoz (Gerente General)',
  emailContacto: 'contacto@pyme-ejemplo.cl',
  ciudadRegion: 'Santiago, Región Metropolitana',
  fechaCreacion: new Date().toLocaleDateString('es-CL'),
};

export const RAT_METHODOLOGY_STEPS = [
  {
    step: '01',
    title: 'Entrevista de Negocio (3 min)',
    desc: 'Preguntas simples y cotidianas sobre las operaciones de tu Pyme: nóminas, CRM, ventas, ecommerce, facturación o cámaras CCTV.',
    icon: 'forum',
    badge: 'Sin jerga legal',
  },
  {
    step: '02',
    title: 'Detección Automática de Sensibles',
    desc: 'El Agente identifica categorías de especial resguardo legal (salud en licencias médicas, biometría en relojes de control, RUT chileno).',
    icon: 'security',
    badge: 'Art. 2 y 16',
  },
  {
    step: '03',
    title: 'Asignación de Base de Licitud',
    desc: 'Fundamenta jurídicamente cada tratamiento conforme a los Artículos 12 y 13 (ejecución contractual, mandato legal, consentimiento o interés legítimo).',
    icon: 'balance',
    badge: 'Art. 12 y 13',
  },
  {
    step: '04',
    title: 'Exportación Oficial APDP',
    desc: 'Descarga inmediata de tu Ficha Oficial del Registro de Actividades de Tratamiento (RAT) en JSON y versión PDF para acreditar diligencia.',
    icon: 'download_for_offline',
    badge: 'Art. 14 ter',
  },
];
